name: Dependabot Commenter

on:
  # issues:
  #   types:
  #     - labeled
  #     - unlabeled
  pull_request:
    types:
      - labeled
      # - unlabeled

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Dependabot Commenter
        if: |
          contains(github.event.issue.labels.*.name, ':shipit: merge') && (github.pull_request.user.login == 'dependabot[bot]' || github.pull_request.user.login == 'dependabot-preview[bot]')
        uses: peaceiris/actions-label-commenter@v1
        with:
          github_token: ${{ secrets.RSG_BOT_TOKEN }}
          config_file: .github/label-commenter-dependabot.yml
